INSERT INTO SAFEBOX_USER (ID, USERNAME, PASSWORD) VALUES ('REGISTERED_USER', 'REGISTERED_USER', '$2a$10$O8sP7LYiwbMwzl2JQbAeOuUVsuROrE.Eiu1x46lUO7e8CjOX4mGAa');
INSERT INTO SAFEBOX_USER_HISTORY (ID, EVENT_DATE, EVENT_TYPE, EVENT_RESULT, LOCKED, CURRENT_TRIES, USER_ID) VALUES ('REGISTERED_USER_HISTORY', CURRENT_DATE - 1, 'CREATION', 'SUCCESSFUL', FALSE, 0, 'REGISTERED_USER');

INSERT INTO SAFEBOX_USER (ID, USERNAME, PASSWORD) VALUES ('LOCKED_USER', 'LOCKED_USER', '$2a$10$zaXPJGy1.0pbwo6KrJnESO.aXkvXJ9IA/IpYNVo6dWN240sjcJgNi');
INSERT INTO SAFEBOX_USER_HISTORY (ID, EVENT_DATE, EVENT_TYPE, EVENT_RESULT, LOCKED, CURRENT_TRIES, USER_ID) VALUES ('LOCKED_USER_HISTORY_0', CURRENT_DATE - 4, 'CREATION', 'SUCCESSFUL', FALSE, 0, 'LOCKED_USER');
INSERT INTO SAFEBOX_USER_HISTORY (ID, EVENT_DATE, EVENT_TYPE, EVENT_RESULT, LOCKED, CURRENT_TRIES, USER_ID) VALUES ('LOCKED_USER_HISTORY_1', CURRENT_DATE - 3, 'LOGIN', 'FAILED', FALSE, 1, 'LOCKED_USER');
INSERT INTO SAFEBOX_USER_HISTORY (ID, EVENT_DATE, EVENT_TYPE, EVENT_RESULT, LOCKED, CURRENT_TRIES, USER_ID) VALUES ('LOCKED_USER_HISTORY_2', CURRENT_DATE - 2, 'LOGIN', 'FAILED', FALSE, 2, 'LOCKED_USER');
INSERT INTO SAFEBOX_USER_HISTORY (ID, EVENT_DATE, EVENT_TYPE, EVENT_RESULT, LOCKED, CURRENT_TRIES, USER_ID) VALUES ('LOCKED_USER_HISTORY_3', CURRENT_DATE - 1, 'LOGIN', 'FAILED', TRUE, 3, 'LOCKED_USER');
