INSERT INTO SAFEBOX (ID, OWNER)
VALUES ('EMPTY_SAFEBOX', 'EMPTY_SAFEBOX');


INSERT INTO SAFEBOX (ID, OWNER)
VALUES ('EXISTING_SAFEBOX', 'EXISTING_SAFEBOX');
INSERT INTO ITEM (ID, DETAIL, SAFEBOX_ID)
VALUES ('ITEM_TEST', 'TEST', 'EXISTING_SAFEBOX');
