openapi: 3.0.0

info:
  description: |
    SafeIsh Holder API - The most secure safebox
  version: 1.0.0
  title: SafeIsh Holder API

paths:
  /safebox:
    post:
      tags:
        - Safebox Holder
      operationId: post-safebox
      summary: Creates a new safebox
      description: |
        Creates a new safebox based on a non-empty name and a password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSafeboxRequest'
      responses:
        '201':
          description: Safebox correctly created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Safebox'
        '409':
          description: Safebox already exists
        '422':
          description: Malformed expected data
        '500':
          description: Unexpected API error
  /safebox/{id}:
    get:
      tags:
        - Safebox Holder
      operationId: get-safebox
      summary: Gets a safebox
      description: |
        Gets a safebox for a given ID
      parameters:
        - in: path
          name: id
          description: Safebox Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Safebox correctly retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Safebox'
        '404':
          description: Safebox does not exist
        '500':
          description: Unexpected API error
  /safebox/{id}/items:
    get:
      tags:
        - Safebox Holder
      operationId: get-safebox-items
      summary: Retrieves the content of a safebox
      description:
        Retrieves the currently stored contents in the safebox identified by the given ID and with the given opening token.
      parameters:
        - in: path
          name: id
          description: Safebox Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Safebox contents correctly retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemList'
        '404':
          description: Requested safebox does not exist
        '422':
          description: Malformed expected data
        '500':
          description: Unexpected API error
    put:
      tags:
        - Safebox Holder
      operationId: put-safebox-items
      summary: Add an items to a Safebox
      description: |
        Inserts new contents in the safebox identified by the given ID and with the given opening token.
      parameters:
        - in: path
          name: id
          description: Safebox id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemList'
      responses:
        '200':
          description: Content correctly added to the safebox
        '404':
          description: Requested safebox does not exist
        '422':
          description: Malformed expected data
        '500':
          description: Unexpected API error
components:
  schemas:
    Safebox:
      description: 'Safebox'
      type: object
      properties:
        id:
          description: Safebox id
          type: string
      required:
        - id
      example:
        id: f626c808-648c-41fe-865d-c6062f3e0899
    ItemList:
      description: Safebox items
      type: object
      properties:
        items:
          description: Safebox items
          type: array
          items:
            type: string
      required:
        - items
      example:
        items:
          - Safebox content 03
          - Safebox content 02
          - Safebox content 01
    CreateSafeboxRequest:
      type: object
      properties:
        owner:
          description: Safebox Owner
          type: string
      required:
        - owner
      example:
        owner: Myself